# Generated by Django 2.2.19 on 2021-04-01 09:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesettingsmodel',
            name='layout',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Layout of the home page'),
        ),
    ]
