# Generated by Django 4.2 on 2024-08-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homenewsmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="homenewsmodel",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="homesettingsmodel",
            name="layout",
            field=models.JSONField(null=True, verbose_name="Layout of the home page"),
        ),
    ]
